# Generated by Django 5.0.6 on 2024-06-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/uploads/cars/"
            ),
        ),
    ]
