# Generated by Django 5.0.6 on 2024-06-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_image"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.AlterField(
            model_name="order",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
    ]
